eventmanager/api/urls.py
from rest_framework.routers import SimpleRouter

from api.views import AccountDetailsViewSet
from api.views import CategoriesViewSet
from api.views import CommentsViewSet
from api.views import EventViewSet
from api.views import InvitationsViewSet
from api.views import TasksViewSet
from api.views import SuggestedCategoriesViewSet


router = SimpleRouter()
router.register("events", EventViewSet, base_name='events')
router.register("comments", CommentsViewSet, base_name='comments')
router.register("categories", CategoriesViewSet, base_name='categories')
router.register(
    "suggested_categories",
    SuggestedCategoriesViewSet,
    base_name='suggested_categories')
router.register("invitations", InvitationsViewSet, base_name='invitations')
router.register("details", AccountDetailsViewSet, base_name='details')
router.register("tasks", TasksViewSet, base_name='tasks')

urlpatterns = router.urls

eventmanager/eventmanager/urls.py
from django.conf.urls import handler404
from django.conf.urls import handler500
from django.conf.urls import url
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include
from django.urls import path
from django.conf.urls import url
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

import notifications.urls

from eventmanager import settings

from rest_framework_swagger.views import get_swagger_view


schema_view = get_swagger_view(title='EventManager API')

urlpatterns = [
    url(r'^jet/', include('jet.urls', 'jet')),
    url(r'^jet/dashboard/', include('jet.dashboard.urls', 'jet-dashboard')),
    path('admin/', admin.site.urls),
    path('', include('accounts.urls')),
    path('events/', include('stats.urls')),
    path('', include('exporting.urls')),
    path('', include('homepage.urls')),
    path('events/', include('events.urls')),
    path('', include('tasks.urls')),
    path('categories/', include('categories.urls')),
    url(
        '^inbox/notifications/',
        include(notifications.urls,
                namespace='notifications')
    ),
    url(r'^api/', include('api.urls')),
    url(r'^api/rest-auth/', include('rest_auth.urls')),
    url(r'^swagger/', schema_view),
    url(r'^oauth/', include('social_django.urls', namespace='social')),
    url(r'^tinymce/', include('tinymce.urls')),
    url(r'hitcount/', include('hitcount.urls', namespace='hitcount')),
] + static(settings.STORAGE_URL, document_root=settings.STORAGE_ROOT) \
  + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

handler404 = 'custom_errors.views.error_404_view'
# handler500 = 'custom_errors.views.error_404_view'

if settings.DEBUG:
    urlpatterns += staticfiles_urlpatterns()

eventmanager/events/urls.py
from . import views

from django.conf.urls import url
from django.contrib.auth import views as auth_views
from django.urls import path

from .feeds import EventFeed
from .feeds import LatestEventFeed


urlpatterns = [
    path(
        'search_json/<int:category_id>/<slug:slug>',
        views.search_json,
        name='events.search_json'
    ),
    path(
        'search_json/<int:category_id>/',
        views.search_json,
        name='events.search_json'
    ),
    path('search/', views.search, name='events.search'),

    path('all/', views.index, name='events.list'),
    path('random/', views.show_random_event, name='events.show_random_event'),
    path('invites/', views.invites, name='events.invites'),
    path('tasks/', views.tasks, name='events.tasks'),
    path('create_event/', views.create_event, name='events.create_event'),
    path('my_events/', views.my_events, name='events.my_events'),
    path('hosted/', views.events_I_host, name='events.events_I_host'),
    path('list/', views.index, name='events.list'),
    path('<slug:slug>', views.show_events_by_slug, name='events.event'),
    path(
        '<slug:slug>/confirm_invite',
        views.confirm_invite,
        name='events.confirm_invite'
    ),
    path(
        '<slug:slug>/decline_invite',
        views.decline_invite,
        name='invites.decline_invite'
    ),
    path('<slug:slug>/delete', views.delete_event_by_slug, name='events.del'),
    path('<slug:slug>/board', views.event_board, name='events.board'),

    path(
        '<slug:slug>/<comment>/delete',
        views.delete_comment_by_slug,
        name='events.comment.del'
    ),

    path(
        '<slug:slug>/<comment>/edit',
        views.edit_comment_by_slug,
        name='events.comment.edit'
    ),


    path('<slug:slug>/edit', views.edit_event, name='events.edit'),
    path(
        '<slug:slug>/add_teammate',
        views.add_teammate,
        name='events.add_teammate'
    ),
    path(
        '<user>/<slug:slug>/add_teammate',
        views.event_team_add,
        name='events.event_team_add'
    ),
    path('<slug:slug>/join', views.join_event, name='events.join'),
    path('<slug:slug>/cancel_join', views.cancel_join, name='events.rm_join'),
    path(
        '<slug:slug>/settings',
        views.visibility_settings,
        name='events.settings'
    ),
    url(r'^feed/$', EventFeed(), name='event_feed'),
    url(r'^latest_feed/$', LatestEventFeed(), name='latest_event_feed'),
    path('<slug:slug>', views.show_events_by_slug, name='event'),
    path(
        'users/<slug:slug>/<event>/invite',
        views.invite,
        name='events.invite'
    ),
]

eventmanager/events/models.py
from accounts.models import AccountDetails

from categories.models import Category

from django.contrib.auth.models import User
from django.core.exceptions import ValidationError
from django.db import models
from django.utils.text import slugify
from django.utils.translation import ugettext as _
from django_countries.fields import CountryField

from mptt.querysets import TreeQuerySet

from datetime import date

from eventmanager.slugify import *

from tinymce.models import HTMLField


def future(value):
    today = date.today()
    if value < today:
        raise ValidationError("Can't add events that have ended")


class EventQuerySet(TreeQuerySet):
    def active(self):
        return self.filter(is_active=True)

    def sort(self):
        return self.order_by('title')


class EventManager(models.Manager):
    def get_queryset(self):
        return EventQuerySet(self.model, using=self._db)

    def active(self):
        return self.get_queryset().active()

    def sort(self):
        return self.get_queryset().sort()


class Event(models.Model):
    title = models.CharField(
        verbose_name=_("Title"),
        help_text=_("250 character limit"),
        max_length=250,
        unique=False,
        null=False,
        blank=False
    )

    slug = models.SlugField(
        unique=True,
        blank=True,
        null=True
    )

    description = HTMLField(
        verbose_name=_("Description"),
        help_text=_("Plain text, any formatting or links will be removed"),
        unique=False,
        null=False,
        blank=False
    )

    location = models.CharField(
        verbose_name=_("Event Location"),
        help_text=_("400 character limit"),
        max_length=400,
        unique=False,
        null=True,
        blank=True
    )

    country = CountryField(
        blank=True,
        null=True
    )

    category = models.ManyToManyField(
        Category,
        verbose_name=_("Categories"),
        help_text=_("Can select many Categories"),
        blank=False,
        related_name="categories"
    )

    visibility = models.CharField(
        verbose_name=_("visibility"),
        unique=False,
        null=False,
        blank=False,
        default='1',
        max_length=2,
    )

    attendees = models.ManyToManyField(
        User,
        verbose_name=_("Attendees"),
        blank=True,
        related_name="attendees"
    )

    team_members = models.ManyToManyField(
        User,
        verbose_name=_("Team"),
        blank=True,
        related_name="team"
    )

    cover_image = models.ImageField(
        upload_to='events',
        blank=True,
        null=True
    )

    is_active = models.BooleanField(
        verbose_name=_("Is active"),
        default=True
    )

    created_at = models.DateTimeField(
        verbose_name=_("Created at"),
        auto_now_add=True
    )

    added_by = models.ForeignKey(
        User,
        null=True,
        blank=True,
        on_delete=models.CASCADE
    )

    updated_at = models.DateTimeField(
        verbose_name=_("Updated at"),
        auto_now=True
    )
    starts_at = models.DateTimeField(
        verbose_name=_("Event starts at"),
        blank=True,
        null=True,
        validators=[future]
    )
    ends_at = models.DateTimeField(
        verbose_name=_("Event ends at"),
        blank=True,
        null=True,
        validators=[future]
    )

    objects = EventManager()

    def save_model(self, request, obj, form, change):
        obj.added_by = request.user
        super().save_model(request, obj, form, change)

    def has_joined_event(user, event_slug):
        try:
            attendees = Event.objects.get(slug=event_slug).attendees.all()
            return user in attendees
        except BaseException:
            return False

    def is_team_member(user, event_slug):
        try:
            team = Event.objects.get(slug=event_slug).team_members.all()
            return user in team
        except BaseException:
            return False

    def get_guests(event_slug):
        attendees = Event.objects.all().get(slug=event_slug).attendees.all()
        filtered_attendees = []
        for user in attendees:
            if AccountDetails.objects.filter(user=user):
                details = AccountDetails.objects.get(user=user)
                user.details = details
                filtered_attendees.append(user)
        return attendees

    def get_categories(event_slug):
        categories = Event.objects.all().get(slug=event_slug).category.all()
        filtered_category = []
        for name in categories:
            filtered_category.append(Category.objects.get(name=name))
        return filtered_category

    def get_category_names(event_slug):
        categories = Event.objects.all().get(slug=event_slug).category.all()
        filtered_category = ""
        for name in categories:
            filtered_category += Category.objects.get(name=name).name + ";"
        return filtered_category

    def can_view_event(event_slug, user):
        event_visibility = Event.objects.all().get(slug=event_slug).visibility
        event = Event.objects.all().get(slug=event_slug)
        has_joined_event = Event.has_joined_event(user, event)

        if has_joined_event:
            return True

        if event_visibility == '1':  # is for everyone
            return True

        if user.is_authenticated:
            if event_visibility == '2':  # is for logged in
                return True
            else:  # is for invited only
                return Invite.is_invited(user, event)
        return False

    def save(self, *args, **kwargs):
        if not self.slug:
            unique_slugify(self, self.title)
        super(Event, self).save(*args, **kwargs)

    class Meta(object):
        verbose_name = _("Event")
        verbose_name_plural = _("Events")
        ordering = ['title']

    def __str__(self):
        return self.title


class CommentQuerySet(TreeQuerySet):
    def active(self):
        return self.filter(is_active=True)

    def sort(self):
        return self.order_by('name')


class CommentManager(models.Manager):
    def get_queryset(self):
        return CommentQuerySet(self.model, using=self._db)

    def active(self):
        return self.get_queryset().active()

    def sort(self):
        return self.get_queryset().sort()


class Comment(models.Model):

    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE
    )

    event = models.ForeignKey(
        'events.Event',
        on_delete=models.CASCADE,
        related_name='comments'
    )

    title = models.CharField(
        verbose_name=_("Title"),
        max_length=120,
        unique=False,
        null=False,
        blank=False
    )

    content = HTMLField(
        verbose_name=_("Content"),
        unique=False,
        null=False,
        blank=False,
        max_length=500
    )

    is_active = models.BooleanField(
        verbose_name=_("Is active"),
        default=True
    )

    created_at = models.DateTimeField(
        verbose_name=_("Created at"),
        auto_now_add=True
    )

    updated_at = models.DateTimeField(
        verbose_name=_("Updated at"),
        auto_now_add=True
    )

    objects = CommentManager()

    class Meta(object):
        verbose_name = _("Comment")
        verbose_name_plural = _("Comments")
        ordering = ['created_at']

    def __str__(self):
        return self.title


class IniviteQuerySet(TreeQuerySet):
    def active(self):
        return self.filter(is_active=True)

    def sort(self):
        return self.order_by('name')


class IniviteManager(models.Manager):
    def get_queryset(self):
        return IniviteQuerySet(self.model, using=self._db)

    def active(self):
        return self.get_queryset().active()

    def sort(self):
        return self.get_queryset().sort()


class Invite(models.Model):

    invited_user = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='invited_user'
    )

    invited_by = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='invited_by'
    )

    event = models.ForeignKey(
        'events.Event',
        on_delete=models.CASCADE,
        related_name='event',
    )

    is_accepted = models.BooleanField(
        verbose_name=_("Is accepted"),
        default=False
    )

    created_at = models.DateTimeField(
        verbose_name=_("Created at"),
        auto_now_add=True
    )

    objects = IniviteManager()

    def is_invited(user, event):
        try:
            invite = Invite.objects.get(event=event, invited_user=user)
            return True
        except BaseException:
            return False

    class Meta(object):
        verbose_name = _("Invite")
        verbose_name_plural = _("Invites")

    def __str__(self):
        return self.invited_user.username

eventmanager/events/forms.py
from django import forms
from django.forms import ModelForm

from events.models import Comment
from events.models import Event

from tasks.models import Task


class EventForm(ModelForm):
    class Meta:
        model = Event
        fields = [
            'title',
            'description',
            'location',
            'country'
        ]


class CommentForm(ModelForm):
    class Meta:
        model = Comment
        fields = [
            'title',
            'content'
        ]


class TaskForm(ModelForm):

    class Meta:
        model = Task
        fields = [
            'title',
            'description',
            'status',
            'assignee'
        ]


class VisibilitySettings(forms.Form):
    Options = (
        ('1', 'Public'),
        ('2', 'Logged users only'),
        ('3', 'Invited only'),
    )
    visibility = forms.ChoiceField(
        label='Choose event visibility',
        widget=forms.Select,
        choices=Options)

    class Meta:
        fields = [
            'visibility',
        ]

eventmanager/events/templates/events/add_comment.html
{% extends 'accounts/base.html' %}
{% load static %}
{% load crispy_forms_tags %}
{% block title %} Edit comment {% endblock %}

{% block content %}
<br>
<h1 class="h1" style="text-align: center;"> Edit comment: </h1>
<form class="well margin-5" method="post">
    {% csrf_token %}
    <h3> {{ form|crispy }} </h3>
    <script type="text/javascript" src="{% static 'scripts/comment_countdown.js' %}"></script>
    <h3> <span id="remainingCount1">  500 chars left  </span>  </h3>

    <h3> <input type="submit" class="btn btn-success btn-block large-form-button" value="Submit"> </h3>
</form>
<br> <br>
{% endblock %}

eventmanager/events/templates/events/add_teammate.html
{% extends 'accounts/base.html' %}
{% load static %}

{% block title %} Add teammate{% endblock %}

{% block head %}
<link href="{% static 'categories/all.css' %}" rel="stylesheet">
<link href="{% static 'accounts/show_account_details.css' %}" rel="stylesheet">
<style type="text/css">
	.textinput, input{
		width: 100%;
	}
</style>
{% endblock %}

{% block content %}

{% include "friends/partials/search_by_username_form.html" with form=form %}
{% include "friends/partials/list_friends.html" with users=users form=form friend_user=False add_to_team=True event=event %}

{% endblock %}

eventmanager/events/templates/events/board.html
{% extends 'accounts/base.html' %}

{% load crispy_forms_tags %}
{% load static %}

{% block title %} Event Board {% endblock %}
{% block head %}
<link href="{% static 'events/event.css' %}" rel="stylesheet">
<link href="{% static 'events/board.css' %}" rel="stylesheet">
{% endblock %}

{% block content %}
{% include "events/partials/add_task_modal.html" with task_form=task_form %}
  <div class="row">
    <div class="col-sm-3 bg-warning">
        <h2 class="heading"> TO DO: <a  data-toggle="modal" href="#add_task"> <i class="fas fa-plus"></i> </a> <hr> </h2>

        {% for task in todo_tickets %}
            {% include "events/partials/task_partial.html" with task=task %}
        {% endfor%}
    </div>


    <div class="col-sm-3 bg-primary">
        <h2 class="heading"> DOING: <a  data-toggle="modal" href="#add_task"> <i class="fas fa-plus"></i> </a> <hr> </h2>

        {% for task in doing_tickets %}
            {% include "events/partials/task_partial.html" with task=task %}
        {% endfor%}
    </div>

    <div class="col-sm-3 bg-success">
        <h2 class="heading"> DONE: <a  data-toggle="modal" href="#add_task"> <i class="fas fa-plus"></i> </a> <hr>  </h2>

        {% for task in done_tickets %}
            {% include "events/partials/task_partial.html" with task=task %}
        {% endfor%}
    </div>
  </div>

{% endblock %}

eventmanager/events/templates/events/create_event.html
{% extends 'accounts/base.html' %}
{% load static %}

{% block title %}
    {% if editing %}
        Edit {{ starts }}
    {% else %}
        Create
    {% endif%}
    event
{% endblock %}

{% block head %}
<link href="{% static 'events/create_event.css' %}" rel="stylesheet">
<script src="https://code.jquery.com/jquery-3.3.1.min.js"></script>

<script src="https://unpkg.com/gijgo@1.9.13/js/gijgo.min.js" type="text/javascript"></script>
<link href="https://unpkg.com/gijgo@1.9.13/css/gijgo.min.css" rel="stylesheet" type="text/css" />
{% endblock %}

{% block content %}
{% load crispy_forms_tags %}
<br>
<h1 class="text-center">
    {% if editing %}
        Edit {{ starts }}{{selected_categories}}
    {% else %}
        Create
    {% endif%}  event:
</h1>

<div class="col-md-8 offset-md-2 centered">
    <form method="post" enctype='multipart/form-data'>
        {% csrf_token %}
        <div class="upload-btn-wrapper">
          <button class="btn btn-block" id="cover_button"> Add cover photo</button>
          <h3> <input type="file" name="cover_image" accept="image/*" id="id_cover_image"> </h3>
          <img id="preview" src="" />
        </div>

         <h3> {{form|crispy}} </h3>
        <br>
        <h3> <b> Categories: </b></h3>
        <select id="category" class="form-control form-control-lg" name="category_select" multiple>
            {% for category in categories %}
            <h3>
                <option  value="{{ category.name }}" name="{{ category.name }}">{{ category.name }}</option>
            </h3>
            {% endfor %}
        </select>
        <br> <br>
        <div class="container">
			<div class="row">
				<div class="col-sm">
					<h3>
						<b> Start time: </b>
						<div class="start_h alert alert-danger hidden"> </div>
					</h3>
					<div class="row">
						<div class="input-group col-sm">
						  <div class="input-group-prepend">
						    <span class="input-group-text" id="basic-addon1"><i class="fa fa-calendar" aria-hidden="true"></i></span>
						  </div>
						  <input  class="form-control" type="date" id="starts_at" name="starts_at" value="{{starts_date}}">
						</div>

						<div class="col-sm">
							<input type="time" id="starts_at_time" name="starts_at_time" value="{{starts_time}}">
						</div>
					</div>
				</div>

				<div class="col-sm">
					<h3>
						<b> End time: </b>
						<div class="end_h alert alert-danger hidden"> </div>
					</h3>
					<div class="row">
						<div class="input-group col-sm">
						  <div class="input-group-prepend">
						    <span class="input-group-text" id="basic-addon1"><i class="fa fa-calendar" aria-hidden="true"></i></span>
						  </div>
						  <input type="date" id="ends_at" class="form-control border" name="ends_at" value="{{ends_date}}">
						</div>

						<div class="col-sm">
						 <input type="time" id="ends_at_time" class="taskDate" name="ends_at_time" value="{{ends_time}}">
						</div>
					</div>
				</div>
			</div>
		</div>

       <script>
           $('#starts_at_time').timepicker({
               uiLibrary: 'bootstrap4'
           });

           $('#ends_at_time').timepicker({
               uiLibrary: 'bootstrap4'
           });
       </script>
        <br> <br>
        <button class="btn btn-primary btn-lg"  type="submit">
            {% if editing %}
              <h3> Edit event </h3>
            {% else %}
              <h3> Create event </h3>
            {% endif%}
        </button>
    </form>
</div>
<br> <br>
<script type="text/javascript" src="{% static 'scripts/textarea_rows.js' %}"></script>
<script type="text/javascript" src="{% static 'scripts/preview_image.js'%}"></script>
<script type="text/javascript" src="{% static 'scripts/validate_event_date.js'%}"></script>
<script type="text/javascript" src="http://weareoutman.github.io/clockpicker/distjquery-clockpicker.min.js"></script>
<script type="text/javascript">
	function selectElement(category) {
		category = '"' + category + '"'
		if(category.length > 2){
			console.log("selecting" + category)
			$('#category option[value=' + category + ']').attr('selected', true);
		}
	}

	var categories = "{{selected_categories}}".split(";");
	categories.forEach(selectElement);
</script>
{% endblock %}

eventmanager/events/templates/events/event.html
{% extends 'accounts/base.html' %}

{% load crispy_forms_tags %}

{% include "accounts/partials/messages_partial.html" with messages=messages %}

{% load static %}

{% block title %} {{event.title}} {% endblock %}

{% block head %}
	<script type='text/javascript' src='//platform-api.sharethis.com/js/sharethis.js#property=5bffb3800624ce0011ee8698&product=inline-share-buttons' async='async'></script>
	<link href="{% static 'events/event.css' %}" rel="stylesheet">
	<link rel="stylesheet" href="{% static 'flags/sprite-hq.css' %}">
	<style type="text/css">
		.bg {
			{% if event.cover_image %}
				background-image: url( "{{ event.cover_image.url }}" );
				height: 70%;
				background-position: center;
				background-repeat: no-repeat;
				background-size: cover;
			{% endif %}
		}
	</style>
{% endblock %}

{% block content %}
	<div class="bg">
		<div class="display-1 edit_delete row">
			<div class="col-xs-6 col-md-10">
				<h1> {{event.title}} </h1>
				{% if event.location %}
					<h3>
						<i class="fa fa-map" aria-hidden="true"></i>
						Location: <i class="flag2x {{ event.country.flag_css }}"></i>, {{ event.location }}
					</h3>
				{% endif %}
			</div>


			<div class="col-xs-6 col-md-2" >
				{% if request.user == event.added_by or is_team_member %}
					<div class="dropdown">
						<button class="btn dropdown-toggle custom-btn large-form-button" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true"  aria-expanded="false">
						Edit
						</button>
						<div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
							<a class="dropdown-item btn-primary large-text" onclick="location.href=window.location.href  + '/delete'" > delete event</a>
							<a class="dropdown-item btn-primary large-text" onclick="location.href=window.location.href  + '/edit'" > edit event</a>
							<a class="dropdown-item btn-primary large-text" onclick="location.href=window.location.href  + '/add_teammate'" > add team </a>
							<a class="dropdown-item btn-primary large-text" onclick="location.href=window.location.href  + '/settings'"> visibility settings </a>
							<a class="dropdown-item btn-primary large-text" onclick="location.href=window.location.href  + '/board'"> event board </a>
							<a class="dropdown-item btn-primary large-text" onclick="location.href=window.location.href  + '/statistics'"> statistics </a>
						</div>
					</div>
				{% endif %}
			</div>
		</div>
	</div>

	{% if request.user.is_authenticated %}
		{% if has_joined %}
			<button class="custom-btn btn-danger btn-primary btn-block   text-uppercase" onclick="location.href=window.location.href  + '/cancel_join'" type="button">
				cancel attendance
			</button>
		{% else %}
			<button class="custom-btn btn-success btn-primary btn-block   text-uppercase" onclick="location.href=window.location.href  + '/join'" type="button">
				join
			</button>
			{% include "accounts/partials/messages_partial.html" with messages=messages %}
		{% endif %}
	{% endif %}

   <div class="row">
	  <div class="col-12"><div class="sharethis-inline-share-buttons"></div></div>
   </div>


	<div class="jumbotron jumbotron-fluid">
	  <div class="container">
		<h1> Event Description:</h1>
		<p class="lead h4 simple start-indent">{{event.description|safe}}</p>
	  </div>
	</div>

	<div class="row">
		<a class="btn col-sm-auto col-md-3 col-lg-3 offset-lg-1 offset-md-1 btn-outline-success h3 btn-lg" data-toggle="modal" href="#guestsModal"> List Guests </a>
		{% include "events/partials/guest_list.html" with guests=guests %}

		<a class="btn col-sm-auto col-md-3 col-lg-3 btn-outline-success h3 btn-lg" data-toggle="modal" href="#teamModal"> List team members </a>
		{% include "events/partials/team_members.html" with team=team %}

		{% if request.user.is_authenticated %}
			<a class="btn col-sm-auto col-md-3 col-lg-4 offset-lg-1 offset-md-1 btn-outline-success h3 btn-lg" data-toggle="modal" href="#inviteModal">
				Invite to event
			</a>
		{% endif %}
	</div>

	<div class="modal hide" id="inviteModal">
		<form class="well" method="post">
			<div class="modal-header">
				<h3 class="h3">Invite to {{event.title}}:</h3>
				<button type="button" class="close" data-dismiss="modal">
					<i class="fa-2x fas fa-times-circle"></i>
				</button>
			</div>
			<div class="modal-body">
				<h3> <b> You can only invite users that you're friends with!</b> </h3>
				<ul>
				   <div class="card-columns">
					{% for user in users%}
						<div class="card-body">
							<div class="card center-text user-details">
								{% include "friends/partials/profile_picture.html" with picture=user.details.profile_picture %}
								<h3> {{name}} </h3>
								<h4> <i class="fa fa-user-circle" aria-hidden="true"></i> {{user.username}} </h4>
								{% if user.details.birth_date %}
									<h4>
										<i class="fa fa-birthday-cake" aria-hidden="true"></i>
										Born on: {{user.details.birth_date}}
									</h4>
								{% endif %}
								<h4> {{user.details.description}} </h4>
								<button class="btn btn-success btn-lg btn-block"  onclick="location.href=window.location.origin + '/events/users/{{user.details.slug}}/{{event.slug}}/invite'" type="button">
										Invite
								</button>
							</div>
						</div>
					{% endfor %}
					</div>
				</ul>
			</div>
		</form>
	</div>
	{% include "events/partials/add_comment_modal.html" with form=form %}
	{% include "events/partials/comments.html" with comments=comments %}
	<br> <br> <br> <br>
{% endblock %}

eventmanager/events/templates/events/my_tasks.html
{% extends 'accounts/base.html' %}

{% load static %}

{% block title %} Tasks {% endblock %}

{% block head %}
<link href="{% static 'events/event.css' %}" rel="stylesheet">
{% endblock %}

{% block content %}
<br> <h1 class="text-center animated fadeInUp slow"> My tasks: </h1> <br>

{% if is_empty%}
	<h2 class="text-center animated fadeInUp slow">
		You have no assigned tasks yet.
	</h2>
{% else %}
<div class="row">
	<div class="col-sm-2"> </div>
	<div class="col-sm-4 bg-warning animated slideInUp">
		<br>
		<h2 class="heading text-center "> TO DO: </h2>
		<br>
		{% for task in todo_tickets %}
		<div class="card tickets">
			<div class="card-body">
				<h2 class="card-title"> {{task.title}}</h2>
				<h3 class="card-subtitle mb-2 text-muted"> event: {{task.event}} </h3>
				<h4 class="card-text">{{task.description}}</h4>
				<a href="/events/{{task.event.slug}}/board" class="card-link"> Go to event board </a>
			</div>
		</div>
		<br>
		{% endfor%}
	</div>
	<div class="col-sm-4 bg-primary animated slideInUp slow">
		<br>
		<h2 class="heading text-center"> DOING:  </h2>
		<br>
		{% for task in doing_tickets %}
		<div class="card">
			<div class="card-body">
				<h2 class="card-title"> {{task.title}}</h2>
				<h3 class="card-subtitle mb-2 text-muted"> event: {{task.event}} </h3>
				<h4 class="card-text">{{task.description}}</h4>
				<a href="/events/{{task.event.slug}}/board" class="card-link"> Go to event board </a>
			</div>
		</div>
		<br>
		{% endfor%}
	</div>
</div>
{% endif %}
<br> <br> <br> <br>
{% endblock %}