eventmanager/accounts/urls.py
from . import views

from django.conf.urls import url
from django.urls import path


urlpatterns = [
    path('signup', views.signup, name='accounts.signup'),
    path('signout', views.signout, name='accounts.signout'),
    path('login', views.login, name='accounts.login'),
    path('delete', views.delete, name='accounts.delete'),
    path('account', views.account_details, name='accounts.account'),
    path(
        'edit_account',
        views.edit_account_details,
        name='accounts.edit_account_details'
    ),
    url(r'^change_password/$', views.change_password, name='change_password'),
    url(
        r'^account_details/$',
        views.show_account_details,
        name='accounts.details'
    ),
    url(r'^change_email/$', views.change_email, name='change_email'),
    path('users', views.list_users, name='accounts.list_users'),
    path(
        'users/<slug:slug>',
        views.gеt_user_by_slug,
        name='accounts.gеt_user_by_slug'
    ),
    path(
        'users/<slug:slug>/friend',
        views.friend,
        name='accounts.add_friend'
    ),
    path(
        'users/<slug:slug>/accept',
        views.accept_request,
        name='accounts.accept_request'
    ),
    path(
        'users/<slug:slug>/decline',
        views.decline_request,
        name='accounts.decline_request'
    ),
    path(
        'users/<slug:slug>/unfriend',
        views.unfriend,
        name='accounts.unfriend'
    ),
    path('friends', views.my_friends, name='accounts.my_friends'),
    path(
        'friends/requests',
        views.list_friendrequests,
        name='accounts.list_friendrequests'
    ),
    path('friends/find', views.search_users, name='accounts.search_users'),

]

eventmanager/api/urls.py
from rest_framework.routers import SimpleRouter

from api.views import AccountDetailsViewSet
from api.views import CategoriesViewSet
from api.views import CommentsViewSet
from api.views import EventViewSet
from api.views import InvitationsViewSet
from api.views import TasksViewSet
from api.views import SuggestedCategoriesViewSet


router = SimpleRouter()
router.register("events", EventViewSet, base_name='events')
router.register("comments", CommentsViewSet, base_name='comments')
router.register("categories", CategoriesViewSet, base_name='categories')
router.register(
    "suggested_categories",
    SuggestedCategoriesViewSet,
    base_name='suggested_categories')
router.register("invitations", InvitationsViewSet, base_name='invitations')
router.register("details", AccountDetailsViewSet, base_name='details')
router.register("tasks", TasksViewSet, base_name='tasks')

urlpatterns = router.urls

eventmanager/eventmanager/urls.py
from django.conf.urls import handler404
from django.conf.urls import handler500
from django.conf.urls import url
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include
from django.urls import path
from django.conf.urls import url
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

import notifications.urls

from eventmanager import settings

from rest_framework_swagger.views import get_swagger_view


schema_view = get_swagger_view(title='EventManager API')

urlpatterns = [
    url(r'^jet/', include('jet.urls', 'jet')),
    url(r'^jet/dashboard/', include('jet.dashboard.urls', 'jet-dashboard')),
    path('admin/', admin.site.urls),
    path('', include('accounts.urls')),
    path('events/', include('stats.urls')),
    path('', include('exporting.urls')),
    path('', include('homepage.urls')),
    path('events/', include('events.urls')),
    path('', include('tasks.urls')),
    path('categories/', include('categories.urls')),
    url(
        '^inbox/notifications/',
        include(notifications.urls,
                namespace='notifications')
    ),
    url(r'^api/', include('api.urls')),
    url(r'^api/rest-auth/', include('rest_auth.urls')),
    url(r'^swagger/', schema_view),
    url(r'^oauth/', include('social_django.urls', namespace='social')),
    url(r'^tinymce/', include('tinymce.urls')),
    url(r'hitcount/', include('hitcount.urls', namespace='hitcount')),
] + static(settings.STORAGE_URL, document_root=settings.STORAGE_ROOT) \
  + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

handler404 = 'custom_errors.views.error_404_view'
# handler500 = 'custom_errors.views.error_404_view'

if settings.DEBUG:
    urlpatterns += staticfiles_urlpatterns()

eventmanager/accounts/models.py
from django.contrib.auth.models import User
from django.db import models
from django.utils.translation import ugettext as _

from eventmanager.slugify import *

from mptt.querysets import TreeQuerySet


class AccountDetailsQuerySet(TreeQuerySet):
    def all(self):
        return self


class AccountDetailsManager(models.Manager):
    def get_queryset(self):
        return AccountDetailsQuerySet(self.model, using=self._db)

    def all(self):
        return self.get_queryset().all()


class AccountDetails(models.Model):
    user = models.ForeignKey(
        User,
        null=True,
        blank=True,
        on_delete=models.CASCADE
    )

    slug = models.SlugField(unique=True, blank=True, null=True)

    profile_picture = models.ImageField(
        upload_to='profile_pictures',
        blank=True,
        null=True
    )

    friends = models.ManyToManyField(
        User,
        verbose_name=_("Friends"),
        blank=True,
        related_name="friends"
    )

    birth_date = models.DateField(("birthdate"), blank=True, null=True)

    description = models.TextField(
        verbose_name=_("Description"),
        help_text=_("Plain text, any formatting or links will be removed"),
        unique=False,
        null=True,
        blank=True
    )

    def is_my_friend(user, friend):
        if AccountDetails.objects.filter(user=user).exists():
            my_details = AccountDetails.objects.get(user=user).friends.all()
            if AccountDetails.objects.filter(user=friend).exists():
                friend_details = AccountDetails.objects.get(
                    user=friend).friends.all()
                if user in friend_details:
                    return True
                if friend in my_details:
                    return True
        return False

    def get_my_friends(user):
        if AccountDetails.objects.filter(user=user).exists():
            friends = AccountDetails.objects.get(user=user).friends.all()

        for friend in friends:
            friend.details = AccountDetails.objects.get(user=friend)

        return friends

    def save_model(self, request, obj, form, change):
        obj.user = request.user
        if not self.slug:
            unique_slugify(self, self.user.username)
        super().save_model(request, obj, form, change)

    class Meta(object):
        verbose_name = _("Account Details")
        verbose_name_plural = _("Account Details")

    def __str__(self):
        if self.slug:
            return "Details for: " + self.slug
        else:
            return "No slug"


class FriendRequestQuerySet(TreeQuerySet):
    def active(self):
        return self.filter(is_active=True)

    def sort(self):
        return self.order_by('name')


class FriendRequestsManager(models.Manager):
    def get_queryset(self):
        return FriendRequestQuerySet(self.model, using=self._db)

    def active(self):
        return self.get_queryset().active()

    def sort(self):
        return self.get_queryset().sort()


class FriendRequest(models.Model):
    sent_by = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='sent_by'
    )

    sent_to = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='sent_to'
    )

    objects = FriendRequestsManager()

    class Meta(object):
        verbose_name = _("Friend Request")
        verbose_name_plural = _("Friend Requests")

    def __str__(self):
        return "FriendRequest"

eventmanager/accounts/forms.py
from accounts.models import *

from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User

from crispy_forms.helper import FormHelper
from crispy_forms.layout import ButtonHolder
from crispy_forms.layout import Field
from crispy_forms.layout import Fieldset
from crispy_forms.layout import Layout
from crispy_forms.layout import Submit

from django.forms import ModelForm


class SignUpForm(UserCreationForm):
    first_name = forms.CharField(
        max_length=30,
        required=False,
        help_text='Optional.'
    )

    last_name = forms.CharField(
        max_length=30,
        required=False,
        help_text='Optional.'
    )
    email = forms.EmailField(max_length=254, help_text='Required.')

    class Meta:
        model = User
        fields = (
            'username',
            'first_name',
            'last_name',
            'email',
            'password1',
            'password2',
        )


class LoginForm(forms.Form):
    username = forms.CharField(
        widget=forms.TextInput(
            attrs={'placeholder': 'Username'}
        )
    )
    password = forms.CharField(
        widget=forms.PasswordInput(
            attrs={'placeholder': 'Password'})
    )
    fields = ['username', 'password']

    username.widget.attrs['class'] = 'formfield'
    password.widget.attrs['class'] = 'formfield'


class ChangeEmailForm(forms.Form):
    original_email = forms.EmailField(max_length=254, help_text='Required.')
    new_email = forms.EmailField(max_length=254, help_text='Required.')

    fields = ['original_email', 'new_email']


class AccountDetailsForm(ModelForm):
    class Meta:
        model = AccountDetails
        fields = [
            'profile_picture',
            'description',
        ]


class UserForm(forms.Form):
    username = forms.CharField(
        widget=forms.TextInput(
            attrs={'placeholder': 'Username'}
        )
    )

    fields = ['username']

eventmanager/accounts/templates/accounts/additonal_account_information.html
{% extends 'accounts/base.html' %}
{% block title %} Additional account info {% endblock %}
{% load crispy_forms_tags %}
{% load static %}
{% block head %}
<link href="{% static 'events/create_event.css' %}" rel="stylesheet">
<style type="text/css">
    textarea{
      width:100%;
    }
</style>
{% endblock %}

{% block content %}
<br> <br>


<div class="col-md-8  offset-md-2 centered" style="padding-bottom: 5%;">
    <form method="post" enctype='multipart/form-data'>
        {% csrf_token %}
        <h4> <b> Profile picture </b> </h4>
        <div class="upload-btn-wrapper">
          <button class="btn btn-block" id="cover_button">  Add profile picture</button>
          <h4> <input type="file" name="profile_picture" accept="image/*" id="id_profile_picture"> </h4>
          <img id="preview" src="" />
        </div>

        <h4> <b> {{ form.description.label }} </b> </h4>
        <h4> {{ form.description }} </h4>
        <h4> <b> Birthdate:</b> <br>
            <input type="date" id="birthdate" class="birthdate" name="birthdate" value="{{birthdate}}">
        </h4>
        <br>
        <button class="btn btn-primary btn-lg btn-block" type="submit">
            <h4> Add info </h4>
        </button>
    </form>
</div>

<script type="text/javascript" src="{% static 'scripts/preview_image.js'%}"></script>
<script type="text/javascript" src="{% static 'scripts/birthday_validator.js'%}"></script>

{% endblock %}

eventmanager/accounts/templates/accounts/base.html
{% load static %}
{% load tags %}

<!DOCTYPE html>
<html lang="en">
    <head>
        <title> {% block title %} {% endblock %} </title>
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.5.0/css/all.css" crossorigin="anonymous">
        <link href="{% static 'base/style/bootstrap.min.css' %}" rel="stylesheet">
        <link href="{% static 'base/style/animate.min.css' %}" rel="stylesheet">
        <link href="{% static 'accounts/base.css' %}" rel="stylesheet">
        <link href="https://fonts.googleapis.com/css?family=Staatliches" rel="stylesheet">
        <link href="https://fonts.googleapis.com/css?family=Montserrat" rel="stylesheet">

        <!-- JavaScript -->
        <script type="text/javascript" src="{% static 'base/scripts/jquery.slim.js' %}"></script>
        <script type="text/javascript" src="{% static 'base/scripts/popper.min.js' %}"></script>
        <script type="text/javascript" src="{% static 'base/scripts/bootstrap.min.js' %}"></script>
        <script type="text/javascript" src="{% static 'base/scripts/jquery.min.js' %}"></script>

        {% block head %} {% endblock %}
    </head>
    <body>
        <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
            <a class="navbar-brand" href="/home">
              <img src="{% static 'pictures/logo-eventmanager.png' %}" alt="logo-eventmanager" style="max-width: 150px;max-height: 150px;" alt="logo eventmanager">
            </a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarSupportedContent">

                <ul class="navbar-nav mr-auto navbar-right">
                    {% if request.user.is_authenticated %}
                    <li class="nav-item dropdown active">
                        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                            <h3> Users </h3>
                        </a>

                        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
	                        <a class="dropdown-item h4" href="/users"> All users </a>
	                        <a class="dropdown-item h4" href="/friends/find"> Search users </a>
	                        <a class="dropdown-item h4" href="/friends"> Friends </a>
	                        <a class="dropdown-item h4" href="/friends/requests"> Friend requests </a>
	                    </div>
                    </li>
                    {% endif %}
                    {% if request.user.is_authenticated %}
	                    <li class="nav-item dropdown active">
	                        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
	                            <h3> Events </h3>
	                        </a>
	                        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
		                        <a class="dropdown-item" href="/events/all/"> <h3> All events </h3> </a>
		                        	<a class="dropdown-item h4" href="/events/create_event/"> Create event </a>
		                        	<a class="dropdown-item h4" href="/events/search/"> Search </a>
		                            <a class="dropdown-item h4" href="/events/my_events/"> My events </a>
		                            <a class="dropdown-item h4" href="/events/hosted/"> Events I host </a>
		                            <a class="dropdown-item h4" href="/events/random/"> Show random event </a>
		                    </div>
	                    </li>
                    {% else %}
	                    <li class="nav-item active">
	                        <a class="nav-link" href="/events/all/">
	                        	<h3> All events </h3>
	                        </a>
	                    </li>
                    {% endif %}

                    {% if request.user.is_authenticated %}
                    <li class="nav-item dropdown active">
                        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                            <h3> Categories </h3>
                        </a>
                        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
	                        <a class="dropdown-item h4" href="/categories/all"> All Categories </a>
	                        <a class="dropdown-item h4" href="/categories/suggested"> Suggested Categories </a>
	                        <a class="dropdown-item h4" href="/categories/suggest_category"> Suggest a category </a>
	                    </div>
                    </li>
                    {% else %}
                    	<li class="nav-item active">
                    	    <a class="nav-link" href="/categories/all">
                    	        <h3> Categories </h3>
                    	    </a>
                    	</li>
                    {% endif %}

                    {% if request.user.is_authenticated %}
                    <li class="nav-item active">
                        <a class="nav-link" href="/events/invites/">
                            <h3>
                            	Invites
                            	{% has_invites user as invites_condition %}
                            	{% if invites_condition %}
                            	<span class="badge badge-light">
                            		{% number_of_invites user %}
                            	</span>
                            	{% endif %}
                            </h3>
                        </a>
                    </li>
                    <li class="nav-item active">
                        <a class="nav-link" href="/events/tasks/">
                            <h3> Tasks </h3>
                        </a>
                    </li>
                    {% endif %}

                    {% block navbar-left %}
                    {% endblock %}

                </ul>

                <ul class="navbar-nav  navbar-right">
                    {% if request.user.is_authenticated %}
                    <li class="nav-item dropdown" style="padding-right: 4vw;">
                        <a class="nav-link dropdown-toggle" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                            <h3> Account info </h3>
                        </a>
                        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
	                        <a class="dropdown-item h4" href="/account_details">
	                        	Account details
	                        </a>
	                        <a class="dropdown-item h4" href="/events/export/">
	                        	Export events
	                        </a>
	                        {% if user.is_authenticated and not backends.associated %}
		                        <a class="dropdown-item h4" href="/change_password">
		                        	Change password
		                        </a>
		                        <a class="dropdown-item h4" href="/change_email">
		                        	Change email
		                        </a>
		                        <a class="dropdown-item h4" href="/delete">
		                        	Delete account
		                        </a>
	                        {% endif %}

	                        {% block navbar-right %}
	                        {% endblock %}

                        	<div class="dropdown-divider"></div>
                            <a class="dropdown-item" href="/signout">
                                <div class = "blue"> <h3 style="font-size: x-large;">  Sign out </h3> </div>
                            </a>
                        </div>
                    </li>
                    {% else %}
                        <a href="/login" class="login h4" style="color: white;text-decoration: none;">
                            Log in
                        </a>
                    {% endif %}
                </ul>
            </div>
        </nav>
        {% block content %}
        {% endblock %}

        <footer class="container-fluid text-center " style="padding-right: 0!important;padding-left: 0!important;">
            <h5 style="font-size: x-large;"> All rights reserved. </h5>
        </footer>
    </body>
</html>

eventmanager/accounts/templates/accounts/change_email.html
{% extends 'accounts/base.html' %}
{% block title %} Change email {% endblock %}

{% load static %}
{% block head %}
<link href="{% static 'background.css' %}" rel="stylesheet">
{% endblock %}

{% block content %}
    {% include "accounts/partials/form_partial.html" with messages=messages form=form button_text="Change email" %}
{% endblock %}

eventmanager/accounts/templates/accounts/change_password.html
{% extends 'accounts/base.html' %}
{% block title %}Change password {% endblock %}
{% load static %}
{% block head %}
<link href="{% static 'background.css' %}" rel="stylesheet">
{% endblock %}


{% block content %}
	{% include "accounts/partials/form_partial.html" with messages=messages form=form button_text="Change Password" %}
	<br> <br>
{% endblock %}

eventmanager/accounts/templates/accounts/delete_profile.html
{% extends 'accounts/base.html' %}
{% load static %}
{% block title %} Delete account {% endblock %}

{% block head %}
<link href="{% static 'accounts/login.css' %}" rel="stylesheet">
<link href="{% static 'accounts/delete.css' %}" rel="stylesheet">
{% endblock %}

{% block content %}
<br> <br>
<div class="col-md"> </div>
<div class="form col-lg-4 offset-lg-4 col-md-8 offset-md-2">
	<form method="post">
			{% csrf_token %}
			{% if wrong_credentials == True %}
				<div class="alert alert-danger alert-dismissible">
					<h4> You entered wrong credentials. </h4>
				</div>
			{% endif%}

			<div class="group form-group">
					<input type="text" class="form-field" required id="id_username" name="username">
					<span class="highlight"></span>
					<span class="bar"></span>
					<label>
						<h4>
							<i class="fa fa-user-circle" aria-hidden="true"></i>
							Username:
						</h4>
						</label>
				</div>

				<div class="group">
					<input type="password" class="form-field" name="password" required id="id_password">
					<span class="highlight"></span>
					<span class="bar"></span>
					<label>
						<h4>
							<i class="fa fa-key" aria-hidden="true"></i>
							Password:
						</h4>
					</label>
				</div>
				<button class="btn btn-danger btn-lg btn-block" type="submit" >
						<h4 style="color: white"> Delete account </h4>
				</button>
				<br>
				<br>
			</form>
</div>
<div class="col-md"> </div>

{% endblock %}

eventmanager/accounts/templates/accounts/home.html
{% extends 'accounts/base.html' %}
{% load static %}
{% block title %}  EventManager {% endblock %}

{% block head %}
<link href="{% static 'accounts/home.css' %}" rel="stylesheet">
<link href="{% static 'accounts/home_animation.css' %}" rel="stylesheet">
{% endblock %}

{% block content %}
<h1 class="h1 text-center animated focus-in-expand welcome">
    Welcome to EventManager, {{request.user}}!
</h1>
<div class="container animated delay-1s focus-in-expand">
    <div class="row">
        <div class="col-lg">
            <a href = "events/create_event/" type="button" class="btn btn-block btn-success">
            	Create event
            </a>
            <br>
        </div>

        <div class="col-lg">
            <a href = "events/all/" type="button" class="btn btn-block btn-primary">
            	Events
            </a> <br>
        </div>
    </div>
    <div class="row">
        <div class="col-lg">
            <a href = "events/invites/" type="button" class="btn btn-block btn-warning">
            	Invites
            </a> <br>
        </div>

        <div class="col-lg">
            <a href = "events/tasks/" type="button" class="btn btn-block btn-danger">
            	Tasks
            </a> <br>
        </div>
    </div>
    <div class="row">
        <div class="col-lg">
            <a href = "events/my_events/" type="button" class="btn btn-block btn-dark">
            	My events
            </a> <br>
        </div>

        <div class="col-lg">
            <a href = "categories/all" type="button" class="btn btn-block btn-light">
            	Browse categories
            </a> <br>
        </div>
    </div>
</div>
<br> <br>
{% endblock %}

eventmanager/accounts/templates/accounts/login.html
{% extends 'accounts/base.html' %}
{% load static %}
{% block title %} Login {% endblock %}

{% block head %}
<link href="{% static 'accounts/login.css' %}" rel="stylesheet">
<style type="text/css">
	input{
		width: 100% !important;
	}
</style>
{% endblock %}

{% block content %}
<br> <br>
<div class="col-md"> </div>
<div class="col-lg-4 offset-lg-4 col-md-8 offset-md-2" style="background-color: white;padding: 5%;border: 4px solid black;  border-radius: 25px;">
   <form method="post">
      {% csrf_token %}
      {% if wrong_credentials == True %}
         <div class="alert alert-danger alert-dismissible" style="margin-bottom: 10%;">
            <h3> You entered wrong credentials. </h3>
         </div>
      {% endif%}

      <div class="group form-group">
           <input type="text" class="form-field" required id="id_username" name="username">
           <span class="highlight"></span>
           <span class="bar"></span>
           <label>
            <h3>
               <i class="fa fa-user-circle" aria-hidden="true"></i>
               Username:
            </h3>
            </label>
         </div>

         <div class="group">
           <input type="password" class="form-field" name="password" required id="id_password">
           <span class="highlight"></span>
           <span class="bar"></span>
           <label>
            <h3>
               <i class="fa fa-key" aria-hidden="true"></i>
               Password:
            </h3>
           </label>
         </div>
         <h3>
            <a href="/signup">
            Don't have account? Register here.
            </a><br>
         </h3>
         <button class="btn btn-primary btn-lg btn-block" type="submit">
            <h3> Log in </h3>
         </button>
         <br>
         <a href="{% url 'social:begin' 'github' %}">
            <button class="btn btn-dark btn-lg btn-block" type="submit">
               <h3> Log in with <i class="fab fa-github "></i> </h3>
            </button>
         </a>
   </form>
</div>
<div class="col-md"> </div>

{% endblock %}

eventmanager/accounts/templates/accounts/show_account_details.html
{% extends 'accounts/base.html' %}
{% load static %}
{% block title %} Account Details {% endblock %}

{% block head %}
<link href="{% static 'accounts/show_account_details.css' %}" rel="stylesheet">
{% endblock %}

{% block content %}
<br> <br>
<div class="col-md-4 offset-md-4 centered class-div">
   {% include "accounts/partials/account_partial.html" with name=name username=username email=email details=details %}
   <a href= "/edit_account" class="btn btn-success btn-block" type="submit">
      <h4> Edit account </h4>
   </a>
</div>
{% endblock %}

eventmanager/accounts/templates/accounts/signup.html
{% extends 'accounts/base.html' %}
{% load static %}
{% block title %} Register {% endblock %}



{% block head %}
<link href="{% static 'accounts/login.css' %}" rel="stylesheet">
<style>

</style>
{% endblock %}

{% block content %}
<br> <br>
<div class="col-md"> </div>
<div class="col-lg-4 offset-lg-4 col-md-8 offset-md-2 signup">
   <form method="post">
        {% csrf_token %}
        {% if wrong_credentials == True %}
            <div class="alert alert-danger alert-dismissible">
                <h3> You entered wrong credentials. </h3>
            </div>
        {% endif%}
        <br>
        <div class="group form-group">
            <input type="text" class="form-field" required id="id_username" name="username">
            <span class="highlight"></span>
            <span class="bar"></span>
            <label>
            <h3>
               <i class="fa fa-user" aria-hidden="true"></i>
               Username:
            </h3>
            </label>
         </div>

        <div class="group">
            <input type="email" class="form-field" name="email" required id="id_email" maxlength="254">
            <span class="highlight"></span>
            <span class="bar"></span>
            <label>
            <h3>
                <i class="fa fa-envelope" aria-hidden="true"></i>
                Email:
            </h3>
           </label>
         </div>

         <div class="group">
            <input type="text" class="form-field" name="first_name" required id="id_first_name">
            <span class="highlight"></span>
            <span class="bar"></span>
            <label>
                <h3>
                   <i class="fa fa-user-circle" aria-hidden="true"></i>
                   First name:
                </h3>
            </label>
         </div>

         <div class="group">
            <input type="text" class="form-field" name="last_name" required id="id_last_name">
            <span class="highlight"></span>
            <span class="bar"></span>
            <label>
                <h3>
                    <i class="fa fa-user-circle" aria-hidden="true"></i>
                    Last name:
                </h3>
            </label>
         </div>

         <div class="group">
            <input type="password" class="form-field" name="password1" required id="id_password1">
            <span class="highlight"></span>
            <span class="bar"></span>
            <label>
                <h3>
                    <i class="fa fa-key" aria-hidden="true"></i>
                    Password:
                </h3>
           </label>
         </div>

         <div class="group">
            <input type="password" class="form-field" name="password2" required id="id_password2">
            <span class="highlight"></span>
            <span class="bar"></span>
            <label>
                <h3>
                   <i class="fa fa-key" aria-hidden="true"></i>
                   Password confirmation:
                </h3>
            </label>
         </div>

        <h3>
            <a href="/login">
            Already have account? Login here. <br>
            </a>
        </h3>
        <button class="btn btn-primary btn-lg btn-block"  type="submit">
            <h3> Sign up </h3>
        </button>
        <br>
   </form>
</div>
<div class="col-md"> </div>
<br> <br> <br> <br>
{% endblock %}

eventmanager/accounts/templates/accounts/user_account.html
{% extends 'accounts/base.html' %}
{% load static %}
{% block title %} Account Details {% endblock %}

{% block head %}
<link href="{% static 'accounts/show_account_details.css' %}" rel="stylesheet">
{% endblock %}

{% block content %}
<br> <br>
<div class="col-md-4 md-offset-4 centered class-div">
    {% include "accounts/partials/account_partial.html" with name=name username=username email=email details=details %}
    {% if not friends %}
    	<button class="btn btn-success btn-lg btn-block large_font" onclick="location.href=window.location.href + '/friend'" type="button">
    		Friend
    	</button>
    {% endif %}

    {% if friends%}
    <button class="btn btn-danger btn-lg btn-block large_font" onclick="location.href=window.location.href + '/unfriend'" type="button">
    	Unfriend
    </button>
    {% endif %}
</div>
<br> <br><br> <br>

{% endblock %}